{
    parserClass='net.mint.MintParser'
    parserUtilClass="net.mint.MintParserUtil"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    elementTypeHolderClass='net.mint.psi.MintElementTypes'

    elementTypeClass='net.mint.psi.MintElementType'
    tokenTypeClass='net.mint.psi.MintTokenType'

    psiClassPrefix='Mint'
    psiImplClassSuffix='Impl'
    psiPackage='net.mint.psi'
    psiImplPackage='net.mint.psi.impl'

    generateTokenAccessors=false

    tokens = [
        BACKTICK =                           "`"
        LEFT_BRACE =                         "{"
        RIGHT_BRACE =                        "}"
        LEFT_PAREN =                         "("
        RIGHT_PAREN =                        ")"
        LEFT_BRACKET =                       "["
        RIGHT_BRACKET =                      "]"
        PIPE =                               "|"
        DOT =                                "."
        COMMA =                              ","
        EQUAL =                              "="
        EQUAL_EQUAL =                        "=="
        BACKSLASH =                          "\\\\"
        RIGHT_ARROW =                        "=>"
        NOT_EQUAL =                          "!="
        NOT =                                "!"
        LEFT_ARROW =                         "<="
        LESS =                               "<"
        GREATER_EQUAL =                      ">="
        GREATER =                            ">"
        PLUS_EQUAL =                         "+="
        PLUS =                               "+"
        MINUS_GREATER =                      "->"
        FUNCTION_PIPE =                      "|>"
        MINUS =                              "-"
        TIMES =                              "*"
        DIVIDENTE =                          "/"
        MODULO =                             "%"
        ARRAY =                              "[]"
        NAMESPACE =                          "::"
        COLON =                              ":"
        AND_AND =                            "&&"
        AND =                                "&"
        OR_OR =                              "||"
        HASH =                               "#"
        DOLLAR =                             "$"
        QUESTION =                           "?"
        SEMI =                               ";"
        CASE =                               "case"
        DO =                                 "do"
        TRY =                                "try"
        ELSE =                               "else"
        IF =                                 "if"
        TRUE =                               "true"
        FALSE =                              "false"
        AS =                                 "as"
        ENCODE =                             "encode"
        DECODE =                             "decode"
        USING =                              "using"
        PROPERTY =                           "property"
        RECORD =                             "record"
        CATCH =                              "catch"
        COMPONENT =                          "component"
        MODULE =                             "module"
        STORE =                              "store"
        STATE =                              "state"
        PROPERTY =                           "property"
        NEXT =                               "next"
        WHERE =                              "where"
        WITH =                               "with"
        FINALLY                              "finally"
        WHEN =                               "when"
        FUN =                                "fun"
        GET =                                "get"
        USE =                                "use"
        ENUM =                               "enum"
        VOID =                               "void"
        PROVIDER =                           "provider"
        ROUTES =                             "routes"
        CONNECT =                            "connect"
        EXPOSING =                           "exposing"
        STYLE =                              "style"
        SLCOMMENT =                          'regexp:/\*.*'
        MLCOMMENT =                          'regexp:/\*.*\n'
        STRING_LITERAL =                     'regexp:("([^\"\\]|\\.)*")'
        NUMBER_LITERAL =                     'regexp:(\+|\-)?(0b[01_]+|0o[0-7_]+|0x[a-fA-f\d_]+|[\d_]+)(\.[\d_]+)?(e[-+]?[\d_]+)?(_?(i|f|u)(8|16|32|64))?'

        CAPITALISED_IDENT   = "regexp:[A-Z]+\w*"
        LOWER_IDENT         = "regexp:\w+"
        space               = 'regexp:\s+'
    ]
}

program ::= statements*

private statements ::= statement [statements]

// This is required to make nonStrictID work - as need an ElementType (LOWER_ID) and a TokenType (LOWER_IDENT)
// nonStrictID doesn't work in Live Preview so replace it with LowerId temporarily while exploring.
LowerId ::= LOWER_IDENT

statement ::=
  'component' ofType '{' statements '}'
 | repeatingRecordAssignments
 | 'store' ofType '{' statements '}'
 | 'fun' <<nonStrictID>> '('? args? ')'? ':' ofType '{' statements '}'
 | 'get' <<nonStrictID>> ':' ofType '{' statements '}'
 | 'if' '(' statements ')' '{' statements '}' 'else' '{' statements '}'
 | '(' recordItems? ')' ':' ofType '=>' '{' statements '}'
 | 'do' '{' statements '}'
 | 'try' '{' statements '}'
 | 'next' '{' recordAssignments '}'
 | 'routes' '{' statements '}'
 | 'module' ofType '{' statements '}'
 | 'record' ofType '{' recordItems '}'
 | ofTypes
 | expressions
 | routeDeclarations
 | 'connect' ofType 'exposing' '{' exports '}'
 | '[]'
 | '[' arrayItems ']'
 | 'catch' ofType '=>' LOWER_IDENT '{' statements '}'
 | 'where' '{' statements '}'
 | 'when' '{' statements '}'
 | 'with' ofType '{' statements '}'
 | enum ofType '{' [statements] '}'
 | 'finally' '{' statements '}'
 | 'case' '(' statements ')' '{' statements '}'
 | '=>'
 | 'void'
 | 'state' <<nonStrictID>> ':' ofType '=' statement
 | 'property' <<nonStrictID>> ':' ofType '=' statement
 | htmls
 | styles
 | operators
 | ops
 | literal
 | useProvider
 | 'decode' LOWER_IDENT 'as' ofType
 | 'encode'
 | 'provider' ofType ':' ofType '{' statements '}'
 | '(' statements ')'
 | '`'

private arrayItems ::= arrayItem [',' arrayItems]
arrayItem ::= statement

useProvider ::=
  'use' ofType '{' [recordAssignments] '}'

private repeatingRecordAssignments ::= repeatingRecordAssignment [',' repeatingRecordAssignments]
private repeatingRecordAssignment ::= '{' recordAssignments '}'

private recordAssignments ::= recordAssignment [ ',' recordAssignments]

private recordAssignment ::= (<<nonStrictID>> '|')? <<nonStrictID>> '=' statements


private styles ::= aStyle [styles]
private aStyle ::= 'style' <<nonStrictID>> '{' CssStatement '}'

operators ::= ('+' | '-'  | '*'  | '/'  | '%'  | '|'  | '^'
                   | '&'  | '>'  | '>=' | '<'  | '<=' | '==' | '!=' | '=' | '|>'
                   | '!')

ops ::= '&&' | '||'

private exports ::= export [',' exports]
private export ::= LOWER_IDENT

private recordItems ::= recordItem [recordItems]
recordItem ::= LOWER_IDENT ':' ofType ('using' STRING_LITERAL)? ','?

private routeDeclarations ::= routeDeclaration [routeDeclarations]
routeDeclaration ::=
   '/' | '*' | LOWER_IDENT | '{' statement '}'

private expressions ::= expression [ops? expressions]
expression ::=
  lhs '=' rhs
  | lhs operators rhs



lhs ::=
 LOWER_IDENT | literal

rhs ::=
 LOWER_IDENT
 | statement


private ofType ::= typePath ['.' ofType]
typePath ::=
     ( CAPITALISED_IDENT | LowerId) (
      '(' repeatingTypeArgs ')'
      | '[' repeatingTypeArgs ']'
     )?

private ofTypes ::= ofType [(','|'::') ofTypes]
private repeatingTypeArgs ::= ofTypes? statements? [',' repeatingTypeArgs]


literal ::= (TRUE
       | FALSE
       | NUMBER_LITERAL
       | STRING_LITERAL)

private args ::= arg [',' args]
arg ::=
  <<nonStrictID>> ':' ofType

// HTML
private htmls ::= html [htmls]
html ::= mintTag | tagOpen | tagEmpty | tagClose

private tagOpen ::= '<' tagName? attrList? '>'
private tagEmpty ::= '<' tagName? attrList? '/' '>'
private tagClose ::= '<' '/' tagName '>'
private mintTag ::= '<' '{' statement '}' '>'


private attrList ::= (attr)*
private attr ::= attrDoubleQuoted | attrComponent | attrEmpty

private tagValues ::= tagValue [tagValues]
private tagValue ::= LOWER_IDENT
      | statement

private attrEmpty ::= attrName
private attrComponent ::= attrName '=' '{'? tagValues '}'?
private attrDoubleQuoted ::= attrName? '=' STRING_LITERAL

tagName ::= LOWER_IDENT ('::' LOWER_IDENT)?
attrName ::= LOWER_IDENT


// CSS
private CssStatement ::=
     CssDeclarations

private CssBlocks ::= CssBlock [CssBlocks]
private CssBlock ::=
   '&' ':'? '::'? CssProperty (':' '::'? CssProperty)? ','? ['{' CssDeclarations '}']

private CssDeclarations ::= CssDeclaration [CssDeclarations]
CssDeclaration ::=
     CssProperty ':' CssValues ';'
     | CssBlocks


private ids ::= id [ids]
private id ::= <<nonStrictID>> | '-' | '::'

private CssProperty ::= ids

private CssValues ::= CssValue [CssValues]
CssValue ::= LOWER_IDENT
         | literal
         | '%'
         | '('
         | ')'
         | '-'
         | '#' CAPITALISED_IDENT? LOWER_IDENT?
         | '.'
         | ':'
         | ','
         | "'"
         | '{' (LOWER_IDENT | literal) '}'